name: BOR UI CD

on:
  push:
    branches:
      - main
    paths:
      - "bor-ui/**"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
          - dev
          - test
          - sandbox
          - prod
      redeploy:
        description: "Redeploy Application"
        required: true
        type: choice
        options:
          - "false"
          - "true"

jobs:
  bor-ui-cd:
    permissions:
      contents: "write"
      id-token: "write"
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-cd.yaml@main
    with:
      target: ${{ inputs.target }}
      node_version: 24
      pnpm_version: 10
      app_name: "bor-ui"
      working_directory: "./bor-ui"
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
