name: BOR UI CI

on:
  pull_request:
    paths:
      - "bor-ui/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./bor-ui
jobs:
  bor-ui-sre-ci:
    permissions:
      contents: "write"
      id-token: "write"
      pull-requests: "write"
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      node_version: 24
      pnpm_version: 11.9.0
      app_name: "bor-ui"
      working_directory: "./bor-ui"
      codecov_flag: "borui"

  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["bor-ui"]
        shardIndex: [1, 2]
        shardTotal: [2]
    defaults:
      run:
        working-directory: ./${{ matrix.project }}
    env:
      CI: true
    container:
      image: mcr.microsoft.com/playwright:v1.60.0-noble
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v6
      with:
        version: 11.9.0
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'
        cache-dependency-path: '${{ matrix.project }}/pnpm-lock.yaml'
    - name: Install dependencies
      run: pnpm install --ignore-scripts
    - name: Nuxt Prepare
      run: pnpm exec nuxt prepare
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    - name: Set basic env
      run: |
        cp .env.example .env
    - name: Run Playwright tests
      run: HOME=/root pnpm test:e2e --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
    - name: Upload blob report to GitHub Actions Artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: blob-report-${{ matrix.shardIndex }}
        path: ${{ matrix.project }}/blob-report
        retention-days: 1
  
  merge-reports:
    if: ${{ !cancelled() }}
    needs: [e2e-tests]
    strategy:
      fail-fast: false
      matrix:
        project: ["bor-ui"]
    defaults:
      run:
        working-directory: ./${{ matrix.project }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ${{ matrix.project }}/all-blob-reports
        pattern: blob-report-*
        merge-multiple: true

    - name: Merge into HTML Report
      run: npx playwright merge-reports --reporter html ./all-blob-reports

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: ${{ matrix.project }}/playwright-report
        retention-days: 2
